### ISSUE TITLE
Add custom functionality with shutdown

### ISSUE THREAD

**Issue by oleg-yudovich** [omrilotan/graceful-shutdown#1]
The services which open connections such Redis, MongoDB, need to close these connections before process termination. It will good to have kind of custom Promise which will resolve all opened connections or list of promises as one of the additional parameters in `graceful` function.
You will await for promise resolve before process termination in graceful or in case of list of promises `Promise.all`.

**Comment by omrilotan** [comment]
Great suggestion.
I think this feature should have two places of implementation:
1. Action(s) to take **before** starting connection terminations
2. Action(s) to take **after** all open connections have been terminated or when procedure has failed.

Let me know if you'd like to take a crack at it - otherwise I'll try to address this soon

**Comment by omrilotan** [comment]
started working on it

**Comment by omrilotan** [comment]
Addressed in [release 2.0.0](https://github.com/omrilotan/graceful-shutdown/releases/tag/2.0.0)
